PROBLEM : I got problems and stuck in understanding of the errors i got {PS C:\Users\maddi\OneDrive\Documents\my_projects\c#> dotnet run app.cs C:\Users\maddi\OneDrive\Documents\my_projects\c#\app.cs(47,9): error CS0127: Since 'ramesh(int)' returns void, a return keyword must not be followed by an object expression C:\Users\maddi\OneDrive\Documents\my_projects\c#\app.cs(51,5): error CS0128: A local variable or function named 'a' is already defined in this scope C:\Users\maddi\OneDrive\Documents\my_projects\c#\app.cs(52,5): error CS0029: Cannot implicitly convert type 'void' to 'bool' C:\Users\maddi\OneDrive\Documents\my_projects\c#\app.cs(45,22): warning CS0162: Unreachable code detected C:\Users\maddi\OneDrive\Documents\my_projects\c#\app.cs(51,5): warning CS0219: The variable 'a' is assigned but its value is never used}